import type { ActiveAbility, PassiveAbility, DamageType, Attribute, SkillName, MonsterCategory, EquipmentQuality } from "./types";

// ========================================
// 主动能力库 (75个) + 评分 (1~10分)
// ========================================

export const ACTIVE_ABILITIES: ActiveAbility[] = [
  // ==================== 造成伤害类 (30个) ====================
  {
    id: "act_01",
    name: "猛击",
    costType: "能量值",
    cost: 2,
    target: "敌对单位",
    effect: { type: "damage", attribute: "力量", damageType: "物理", bonus: 1 },
    description: "应用【力量】进行攻击检定，造成【物理】伤害，本次攻击检定额外+1",
    score: 4,
  },
  {
    id: "act_02",
    name: "烈焰斩",
    costType: "能量值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "damage", attribute: "力量", damageType: "火焰", bonus: 2 },
    description: "应用【力量】进行攻击检定，造成【火焰】伤害，本次攻击检定额外+2",
    score: 5,
  },
  {
    id: "act_03",
    name: "寒冰箭",
    costType: "能量值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "damage", attribute: "智力", damageType: "冰霜", bonus: 1 },
    description: "应用【智力】进行攻击检定，造成【冰霜】伤害，本次攻击检定额外+1",
    score: 4,
  },
  {
    id: "act_04",
    name: "暗影突袭",
    costType: "能量值",
    cost: 4,
    target: "敌对单位",
    effect: { type: "damage", attribute: "敏捷", damageType: "黑暗", bonus: 2 },
    description: "应用【敏捷】进行攻击检定，造成【黑暗】伤害，本次攻击检定额外+2",
    score: 5,
  },
  {
    id: "act_05",
    name: "圣光打击",
    costType: "能量值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "damage", attribute: "意志", damageType: "光明", bonus: 1 },
    description: "应用【意志】进行攻击检定，造成【光明】伤害，本次攻击检定额外+1",
    score: 4,
  },
  {
    id: "act_06",
    name: "双重斩击",
    costType: "能量值",
    cost: 4,
    target: "敌对单位",
    effect: { type: "combo", bonus: 0, extraNormalAttackOnHit: true },
    description: "应用【敏捷】进行攻击检定，造成【物理】伤害，若命中可再次进行1次普通攻击",
    score: 7,
  },
  {
    id: "act_07",
    name: "火焰风暴",
    costType: "能量值",
    cost: 6,
    target: "所有敌对单位",
    effect: { type: "damage", attribute: "智力", damageType: "火焰", bonus: 1 },
    description: "应用【智力】对所有敌对单位进行攻击检定，造成【火焰】伤害，本次攻击检定额外+1",
    score: 8,
  },
  {
    id: "act_08",
    name: "冰霜新星",
    costType: "能量值",
    cost: 5,
    target: "所有敌对单位",
    effect: { type: "damage", attribute: "智力", damageType: "冰霜", bonus: 0 },
    description: "应用【智力】对所有敌对单位进行攻击检定，造成【冰霜】伤害",
    score: 6,
  },
  {
    id: "act_09",
    name: "破甲打击",
    costType: "能量值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "damage", attribute: "力量", damageType: "物理", bonus: 3 },
    description: "应用【力量】进行攻击检定，造成【物理】伤害，本次攻击检定额外+3",
    score: 7,
  },
  {
    id: "act_10",
    name: "精准射击",
    costType: "能量值",
    cost: 2,
    target: "敌对单位",
    effect: { type: "damage", attribute: "敏捷", damageType: "物理", bonus: 2 },
    description: "应用【敏捷】进行攻击检定，造成【物理】伤害，本次攻击检定额外+2",
    score: 5,
  },
  {
    id: "act_11",
    name: "黑暗侵蚀",
    costType: "能量值",
    cost: 4,
    target: "敌对单位",
    effect: { type: "damage", attribute: "智力", damageType: "黑暗", bonus: 2 },
    description: "应用【智力】进行攻击检定，造成【黑暗】伤害，本次攻击检定额外+2",
    score: 5,
  },
  {
    id: "act_12",
    name: "光明审判",
    costType: "能量值",
    cost: 5,
    target: "敌对单位",
    effect: { type: "damage", attribute: "意志", damageType: "光明", bonus: 3 },
    description: "应用【意志】进行攻击检定，造成【光明】伤害，本次攻击检定额外+3",
    score: 7,
  },
  {
    id: "act_13",
    name: "狂暴挥砍",
    costType: "生命值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "damage", attribute: "力量", damageType: "物理", bonus: 2 },
    description: "消耗3点生命值，应用【力量】进行攻击检定，造成【物理】伤害，本次攻击检定额外+2",
    score: 6,
  },
  {
    id: "act_14",
    name: "雷电冲击",
    costType: "能量值",
    cost: 4,
    target: "敌对单位",
    effect: { type: "damage", attribute: "智力", damageType: "闪电", bonus: 2 },
    description: "应用【智力】进行攻击检定，造成【闪电】伤害，本次攻击检定额外+2",
    score: 5,
  },
  {
    id: "act_15",
    name: "剧毒之刃",
    costType: "能量值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "damage", attribute: "敏捷", damageType: "黑暗", bonus: 1 },
    description: "应用【敏捷】进行攻击检定，造成【黑暗】伤害，本次攻击检定额外+1",
    score: 4,
  },
  {
    id: "act_16",
    name: "灵魂收割",
    costType: "能量值",
    cost: 5,
    target: "敌对单位",
    effect: { type: "damage", attribute: "意志", damageType: "黑暗", bonus: 2 },
    description: "应用【意志】进行攻击检定，造成【黑暗】伤害，本次攻击检定额外+2",
    score: 6,
  },
  {
    id: "act_17",
    name: "神圣冲击",
    costType: "能量值",
    cost: 4,
    target: "敌对单位",
    effect: { type: "damage", attribute: "意志", damageType: "光明", bonus: 2 },
    description: "应用【意志】进行攻击检定，造成【光明】伤害，本次攻击检定额外+2",
    score: 6,
  },
  {
    id: "act_18",
    name: "旋风斩",
    costType: "能量值",
    cost: 5,
    target: "所有敌对单位",
    effect: { type: "damage", attribute: "力量", damageType: "物理", bonus: 1 },
    description: "应用【力量】对所有敌对单位进行攻击检定，造成【物理】伤害，本次攻击检定额外+1",
    score: 8,
  },
  {
    id: "act_19",
    name: "冰冻射线",
    costType: "能量值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "damage", attribute: "智力", damageType: "冰霜", bonus: 2 },
    description: "应用【智力】进行攻击检定，造成【冰霜】伤害，本次攻击检定额外+2",
    score: 5,
  },
  {
    id: "act_20",
    name: "燃烧之触",
    costType: "能量值",
    cost: 2,
    target: "敌对单位",
    effect: { type: "damage", attribute: "智力", damageType: "火焰", bonus: 1 },
    description: "应用【智力】进行攻击检定，造成【火焰】伤害，本次攻击检定额外+1",
    score: 3,
  },
  {
    id: "act_21",
    name: "雷霆一击",
    costType: "能量值",
    cost: 5,
    target: "敌对单位",
    effect: { type: "damage", attribute: "力量", damageType: "闪电", bonus: 2 },
    description: "应用【力量】进行攻击检定，造成【闪电】伤害，本次攻击检定额外+2",
    score: 5,
  },
  {
    id: "act_22",
    name: "暗影箭",
    costType: "能量值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "damage", attribute: "智力", damageType: "黑暗", bonus: 1 },
    description: "应用【智力】进行攻击检定，造成【黑暗】伤害，本次攻击检定额外+1",
    score: 3,
  },
  {
    id: "act_23",
    name: "神圣之锤",
    costType: "能量值",
    cost: 4,
    target: "敌对单位",
    effect: { type: "damage", attribute: "力量", damageType: "光明", bonus: 2 },
    description: "应用【力量】进行攻击检定，造成【光明】伤害，本次攻击检定额外+2",
    score: 5,
  },
  {
    id: "act_24",
    name: "连环闪电",
    costType: "能量值",
    cost: 5,
    target: "所有敌对单位",
    effect: { type: "damage", attribute: "智力", damageType: "闪电", bonus: 0 },
    description: "应用【智力】对所有敌对单位进行攻击检定，造成【闪电】伤害",
    score: 6,
  },
  {
    id: "act_25",
    name: "噬魂斩",
    costType: "能量值",
    cost: 4,
    target: "敌对单位",
    effect: { type: "damage", attribute: "意志", damageType: "黑暗", bonus: 1, healSelf: 0, drainEnergy: 2 },
    description: "应用【意志】进行攻击检定，造成【黑暗】伤害，本次攻击检定额外+1，若命中恢复自身2点能量值",
    score: 7,
  },
  {
    id: "act_26",
    name: "烈焰风暴(意志)",
    costType: "能量值",
    cost: 6,
    target: "所有敌对单位",
    effect: { type: "damage", attribute: "意志", damageType: "火焰", bonus: 2 },
    description: "应用【意志】对所有敌对单位进行攻击检定，造成【火焰】伤害，本次攻击检定额外+2",
    score: 8,
  },
  {
    id: "act_27",
    name: "霜冻之环",
    costType: "能量值",
    cost: 4,
    target: "所有敌对单位",
    effect: { type: "damage", attribute: "智力", damageType: "冰霜", bonus: 1 },
    description: "应用【智力】对所有敌对单位进行攻击检定，造成【冰霜】伤害，本次攻击检定额外+1",
    score: 7,
  },
  {
    id: "act_28",
    name: "光明之刃",
    costType: "能量值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "damage", attribute: "敏捷", damageType: "光明", bonus: 2 },
    description: "应用【敏捷】进行攻击检定，造成【光明】伤害，本次攻击检定额外+2",
    score: 5,
  },
  {
    id: "act_29",
    name: "虚空撕裂",
    costType: "能量值",
    cost: 5,
    target: "敌对单位",
    effect: { type: "damage", attribute: "智力", damageType: "黑暗", bonus: 3 },
    description: "应用【智力】进行攻击检定，造成【黑暗】伤害，本次攻击检定额外+3",
    score: 7,
  },
  {
    id: "act_30",
    name: "雷霆万钧",
    costType: "能量值",
    cost: 6,
    target: "所有敌对单位",
    effect: { type: "damage", attribute: "力量", damageType: "闪电", bonus: 2 },
    description: "应用【力量】对所有敌对单位进行攻击检定，造成【闪电】伤害，本次攻击检定额外+2",
    score: 9,
  },

  // ==================== 增益类 (23个) ====================
  {
    id: "act_31",
    name: "治疗术",
    costType: "能量值",
    cost: 3,
    target: "友方单位",
    effect: { type: "heal", hp: 3 },
    description: "恢复目标3点生命值",
    score: 5,
  },
  {
    id: "act_32",
    name: "群体治疗",
    costType: "能量值",
    cost: 6,
    target: "所有友方单位",
    effect: { type: "heal", hp: 2 },
    description: "恢复所有友方单位2点生命值",
    score: 7,
  },
  {
    id: "act_33",
    name: "能量灌注",
    costType: "能量值",
    cost: 2,
    target: "友方单位",
    effect: { type: "heal", ep: 3 },
    description: "恢复目标3点能量值",
    score: 5,
  },
  {
    id: "act_34",
    name: "闪避姿态",
    costType: "能量值",
    cost: 2,
    target: "自己",
    effect: { type: "buff_dodge", value: 2, duration: 3 },
    description: "闪避值+2，持续3回合",
    score: 5,
  },
  {
    id: "act_35",
    name: "铁壁防御",
    costType: "能量值",
    cost: 3,
    target: "自己",
    effect: { type: "buff_block", value: 2, duration: 3 },
    description: "格挡值+2，持续3回合",
    score: 5,
  },
  {
    id: "act_36",
    name: "火焰护盾",
    costType: "能量值",
    cost: 3,
    target: "自己",
    effect: { type: "buff_resistance", damageTypes: ["火焰"], duration: 4 },
    description: "获得【火焰】抗性，持续4回合",
    score: 4,
  },
  {
    id: "act_37",
    name: "冰霜护甲",
    costType: "能量值",
    cost: 3,
    target: "自己",
    effect: { type: "buff_resistance", damageTypes: ["冰霜"], duration: 4 },
    description: "获得【冰霜】抗性，持续4回合",
    score: 4,
  },
  {
    id: "act_38",
    name: "暗影庇护",
    costType: "能量值",
    cost: 3,
    target: "自己",
    effect: { type: "buff_resistance", damageTypes: ["黑暗"], duration: 4 },
    description: "获得【黑暗】抗性，持续4回合",
    score: 4,
  },
  {
    id: "act_39",
    name: "圣光庇护",
    costType: "能量值",
    cost: 3,
    target: "自己",
    effect: { type: "buff_resistance", damageTypes: ["光明"], duration: 4 },
    description: "获得【光明】抗性，持续4回合",
    score: 4,
  },
  {
    id: "act_40",
    name: "战斗怒吼",
    costType: "能量值",
    cost: 4,
    target: "所有友方单位",
    effect: { type: "buff_attack", value: 1, duration: 3 },
    description: "所有友方单位攻击加值+1，持续3回合",
    score: 7,
  },
  {
    id: "act_41",
    name: "力量强化",
    costType: "能量值",
    cost: 3,
    target: "友方单位",
    effect: { type: "buff_attribute", attribute: "力量", value: 2, duration: 3 },
    description: "目标力量+2，持续3回合",
    score: 5,
  },
  {
    id: "act_42",
    name: "敏捷强化",
    costType: "能量值",
    cost: 3,
    target: "友方单位",
    effect: { type: "buff_attribute", attribute: "敏捷", value: 2, duration: 3 },
    description: "目标敏捷+2，持续3回合",
    score: 5,
  },
  {
    id: "act_43",
    name: "智力强化",
    costType: "能量值",
    cost: 3,
    target: "友方单位",
    effect: { type: "buff_attribute", attribute: "智力", value: 2, duration: 3 },
    description: "目标智力+2，持续3回合",
    score: 5,
  },
  {
    id: "act_44",
    name: "意志强化",
    costType: "能量值",
    cost: 3,
    target: "友方单位",
    effect: { type: "buff_attribute", attribute: "意志", value: 2, duration: 3 },
    description: "目标意志+2，持续3回合",
    score: 5,
  },
  {
    id: "act_45",
    name: "复苏",
    costType: "能量值",
    cost: 5,
    target: "友方单位",
    effect: { type: "heal", hp: 5, ep: 2 },
    description: "恢复目标5点生命值，恢复目标2点能量值",
    score: 8,
  },
  {
    id: "act_46",
    name: "闪电护盾",
    costType: "能量值",
    cost: 3,
    target: "自己",
    effect: { type: "buff_resistance", damageTypes: ["闪电"], duration: 4 },
    description: "获得【闪电】抗性，持续4回合",
    score: 4,
  },
  {
    id: "act_47",
    name: "群体能量灌注",
    costType: "能量值",
    cost: 5,
    target: "所有友方单位",
    effect: { type: "heal", ep: 2 },
    description: "恢复所有友方单位2点能量值",
    score: 7,
  },
  {
    id: "act_48",
    name: "神圣庇护",
    costType: "能量值",
    cost: 4,
    target: "友方单位",
    effect: { type: "buff_resistance", damageTypes: ["光明", "黑暗"], duration: 3 },
    description: "获得【光明】抗性、【黑暗】抗性，持续3回合",
    score: 6,
  },
  {
    id: "act_49",
    name: "全面强化",
    costType: "能量值",
    cost: 6,
    target: "友方单位",
    effect: { type: "multi_buff", attack: 1, dodge: 1, duration: 3 },
    description: "目标攻击加值+1，闪避值+1，持续3回合",
    score: 6,
  },
  {
    id: "act_50",
    name: "物理护盾",
    costType: "能量值",
    cost: 3,
    target: "自己",
    effect: { type: "buff_resistance", damageTypes: ["物理"], duration: 4 },
    description: "获得【物理】抗性，持续4回合",
    score: 5,
  },
  {
    id: "act_51",
    name: "战斗狂热",
    costType: "能量值",
    cost: 4,
    target: "自己",
    effect: { type: "buff_attack", value: 2, duration: 2 },
    description: "攻击加值+2，持续2回合",
    score: 6,
  },
  {
    id: "act_52",
    name: "元素护甲",
    costType: "能量值",
    cost: 5,
    target: "自己",
    effect: { type: "buff_resistance", damageTypes: ["火焰", "冰霜", "闪电"], duration: 3 },
    description: "获得【火焰】抗性、【冰霜】抗性、【闪电】抗性，持续3回合",
    score: 7,
  },
  {
    id: "act_53",
    name: "生命链接",
    costType: "能量值",
    cost: 4,
    target: "友方单位",
    effect: { type: "heal", hp: 4 },
    description: "恢复目标4点生命值，自身恢复2点生命值",
    score: 7,
  },

  // ==================== 减益类 (22个) ====================
  {
    id: "act_54",
    name: "致盲",
    costType: "能量值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "debuff_dodge", value: 2, duration: 3 },
    description: "目标闪避值-2，持续3回合",
    score: 5,
  },
  {
    id: "act_55",
    name: "破甲",
    costType: "能量值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "debuff_block", value: 2, duration: 3 },
    description: "目标格挡值-2，持续3回合",
    score: 5,
  },
  {
    id: "act_56",
    name: "火焰诅咒",
    costType: "能量值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "debuff_vulnerable", damageTypes: ["火焰"], duration: 4 },
    description: "目标获得【火焰】易伤，持续4回合",
    score: 4,
  },
  {
    id: "act_57",
    name: "冰霜诅咒",
    costType: "能量值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "debuff_vulnerable", damageTypes: ["冰霜"], duration: 4 },
    description: "目标获得【冰霜】易伤，持续4回合",
    score: 4,
  },
  {
    id: "act_58",
    name: "黑暗诅咒",
    costType: "能量值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "debuff_vulnerable", damageTypes: ["黑暗"], duration: 4 },
    description: "目标获得【黑暗】易伤，持续4回合",
    score: 4,
  },
  {
    id: "act_59",
    name: "光明诅咒",
    costType: "能量值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "debuff_vulnerable", damageTypes: ["光明"], duration: 4 },
    description: "目标获得【光明】易伤，持续4回合",
    score: 4,
  },
  {
    id: "act_60",
    name: "虚弱",
    costType: "能量值",
    cost: 4,
    target: "敌对单位",
    effect: { type: "debuff_attack", value: 2, duration: 3 },
    description: "目标攻击加值-2，持续3回合",
    score: 6,
  },
  {
    id: "act_61",
    name: "力量削弱",
    costType: "能量值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "debuff_attribute", attribute: "力量", value: 2, duration: 3 },
    description: "目标力量-2，持续3回合",
    score: 5,
  },
  {
    id: "act_62",
    name: "敏捷削弱",
    costType: "能量值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "debuff_attribute", attribute: "敏捷", value: 2, duration: 3 },
    description: "目标敏捷-2，持续3回合",
    score: 5,
  },
  {
    id: "act_63",
    name: "智力削弱",
    costType: "能量值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "debuff_attribute", attribute: "智力", value: 2, duration: 3 },
    description: "目标智力-2，持续3回合",
    score: 5,
  },
  {
    id: "act_64",
    name: "意志削弱",
    costType: "能量值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "debuff_attribute", attribute: "意志", value: 2, duration: 3 },
    description: "目标意志-2，持续3回合",
    score: 5,
  },
  {
    id: "act_65",
    name: "恐惧嚎叫",
    costType: "能量值",
    cost: 5,
    target: "所有敌对单位",
    effect: { type: "debuff_attack", value: 1, duration: 2 },
    description: "所有敌对单位攻击加值-1，持续2回合",
    score: 6,
  },
  {
    id: "act_66",
    name: "混乱之触",
    costType: "能量值",
    cost: 4,
    target: "敌对单位",
    effect: { type: "multi_buff", dodge: -1, block: -1, duration: 3 },
    description: "目标闪避值-1，格挡值-1，持续3回合",
    score: 5,
  },
  {
    id: "act_67",
    name: "元素剥离",
    costType: "能量值",
    cost: 4,
    target: "敌对单位",
    effect: { type: "debuff_vulnerable", damageTypes: ["火焰", "冰霜"], duration: 3 },
    description: "目标获得【火焰】易伤、【冰霜】易伤，持续3回合",
    score: 6,
  },
  {
    id: "act_68",
    name: "灵魂震慑",
    costType: "能量值",
    cost: 5,
    target: "敌对单位",
    effect: { type: "multi_buff", attack: -2, dodge: -1, duration: 3 },
    description: "目标攻击加值-2，闪避值-1，持续3回合",
    score: 6,
  },
  {
    id: "act_69",
    name: "闪电诅咒",
    costType: "能量值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "debuff_vulnerable", damageTypes: ["闪电"], duration: 4 },
    description: "目标获得【闪电】易伤，持续4回合",
    score: 4,
  },
  {
    id: "act_70",
    name: "物理诅咒",
    costType: "能量值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "debuff_vulnerable", damageTypes: ["物理"], duration: 4 },
    description: "目标获得【物理】易伤，持续4回合",
    score: 5,
  },
  {
    id: "act_71",
    name: "群体虚弱",
    costType: "能量值",
    cost: 6,
    target: "所有敌对单位",
    effect: { type: "debuff_attack", value: 1, duration: 3 },
    description: "所有敌对单位攻击加值-1，持续3回合",
    score: 7,
  },
  {
    id: "act_72",
    name: "元素诅咒",
    costType: "能量值",
    cost: 5,
    target: "敌对单位",
    effect: { type: "debuff_vulnerable", damageTypes: ["火焰", "冰霜", "闪电"], duration: 3 },
    description: "目标获得【火焰】易伤、【冰霜】易伤、【闪电】易伤，持续3回合",
    score: 7,
  },
  {
    id: "act_73",
    name: "能量枯竭",
    costType: "能量值",
    cost: 4,
    target: "敌对单位",
    effect: { type: "debuff_max_energy", value: 3, duration: 3 },
    description: "目标能量值上限-3，持续3回合",
    score: 6,
  },
  {
    id: "act_74",
    name: "致残打击",
    costType: "能量值",
    cost: 3,
    target: "敌对单位",
    effect: { type: "multi_buff", dodge: -1, duration: 3 },
    description: "目标敏捷-1，闪避值-1，持续3回合",
    score: 4,
  },
  {
    id: "act_75",
    name: "恐惧凝视",
    costType: "能量值",
    cost: 5,
    target: "敌对单位",
    effect: { type: "multi_buff", attack: -1, block: -2, duration: 3 },
    description: "目标攻击加值-1，格挡值-2，持续3回合",
    score: 6,
  },
];

// ========================================
// 被动能力库 (77个) + 评分 (1~10分)
// ========================================

export const PASSIVE_ABILITIES: PassiveAbility[] = [
  // ==================== 属性增强类 (19个) ====================
  { id: "pas_01", name: "力量强化", effect: { type: "attribute", attribute: "力量", value: 1 }, description: "力量+1", score: 2 },
  { id: "pas_02", name: "敏捷强化", effect: { type: "attribute", attribute: "敏捷", value: 1 }, description: "敏捷+1", score: 2 },
  { id: "pas_03", name: "智力强化", effect: { type: "attribute", attribute: "智力", value: 1 }, description: "智力+1", score: 2 },
  { id: "pas_04", name: "意志强化", effect: { type: "attribute", attribute: "意志", value: 1 }, description: "意志+1", score: 2 },
  { id: "pas_05", name: "超凡力量", effect: { type: "attribute", attribute: "力量", value: 2 }, description: "力量+2", score: 4 },
  { id: "pas_06", name: "超凡敏捷", effect: { type: "attribute", attribute: "敏捷", value: 2 }, description: "敏捷+2", score: 4 },
  { id: "pas_07", name: "超凡智力", effect: { type: "attribute", attribute: "智力", value: 2 }, description: "智力+2", score: 4 },
  { id: "pas_08", name: "超凡意志", effect: { type: "attribute", attribute: "意志", value: 2 }, description: "意志+2", score: 4 },
  { id: "pas_09", name: "全能强化", effect: { type: "attribute", attribute: "力量", value: 1 }, description: "力量+1，敏捷+1", score: 4 },
  { id: "pas_10", name: "心智强化", effect: { type: "attribute", attribute: "智力", value: 1 }, description: "智力+1，意志+1", score: 4 },
  { id: "pas_11", name: "体魄强化", effect: { type: "attribute", attribute: "力量", value: 1 }, description: "力量+1，意志+1", score: 4 },
  { id: "pas_12", name: "灵巧强化", effect: { type: "attribute", attribute: "敏捷", value: 1 }, description: "敏捷+1，智力+1", score: 4 },
  { id: "pas_13", name: "传奇之力", effect: { type: "attribute", attribute: "力量", value: 1 }, description: "力量+1，敏捷+1，智力+1", score: 5 },
  { id: "pas_14", name: "传奇之心", effect: { type: "attribute", attribute: "智力", value: 1 }, description: "智力+1，意志+1，力量+1", score: 5 },
  { id: "pas_15", name: "完美平衡", effect: { type: "attribute", attribute: "力量", value: 1 }, description: "力量+1，敏捷+1，智力+1，意志+1", score: 6 },
  { id: "pas_16", name: "极限力量", effect: { type: "attribute", attribute: "力量", value: 3 }, description: "力量+3", score: 5 },
  { id: "pas_17", name: "极限敏捷", effect: { type: "attribute", attribute: "敏捷", value: 3 }, description: "敏捷+3", score: 5 },
  { id: "pas_18", name: "极限智力", effect: { type: "attribute", attribute: "智力", value: 3 }, description: "智力+3", score: 5 },
  { id: "pas_19", name: "极限意志", effect: { type: "attribute", attribute: "意志", value: 3 }, description: "意志+3", score: 5 },

  // ==================== 防御增强类 (15个) ====================
  { id: "pas_20", name: "战斗直觉", effect: { type: "dodge", value: 1 }, description: "闪避值+1", score: 3 },
  { id: "pas_21", name: "高级闪避", effect: { type: "dodge", value: 2 }, description: "闪避值+2", score: 5 },
  { id: "pas_22", name: "格挡精通", effect: { type: "block", value: 1 }, description: "格挡值+1", score: 3 },
  { id: "pas_23", name: "高级格挡", effect: { type: "block", value: 2 }, description: "格挡值+2", score: 5 },
  { id: "pas_24", name: "全面防御", effect: { type: "dodge", value: 1 }, description: "闪避值+1，格挡值+1", score: 5 },
  { id: "pas_25", name: "坚韧体魄", effect: { type: "max_hp", value: 3 }, description: "生命值上限+3", score: 4 },
  { id: "pas_26", name: "旺盛生命", effect: { type: "max_hp", value: 5 }, description: "生命值上限+5", score: 6 },
  { id: "pas_27", name: "魔法亲和", effect: { type: "max_energy", value: 3 }, description: "能量值上限+3", score: 4 },
  { id: "pas_28", name: "能量充沛", effect: { type: "max_energy", value: 5 }, description: "能量值上限+5", score: 6 },
  { id: "pas_29", name: "生存专家\(防御\)", effect: { type: "max_hp", value: 2 }, description: "生命值上限+2，能量值上限+2", score: 5 },
  { id: "pas_30", name: "闪避大师", effect: { type: "dodge", value: 3 }, description: "闪避值+3", score: 6 },
  { id: "pas_31", name: "格挡大师", effect: { type: "block", value: 3 }, description: "格挡值+3", score: 6 },
  { id: "pas_32", name: "钢铁意志", effect: { type: "max_hp", value: 4 }, description: "生命值上限+4，能量值上限+2", score: 6 },
  { id: "pas_33", name: "生命源泉", effect: { type: "max_hp", value: 7 }, description: "生命值上限+7", score: 7 },
  { id: "pas_34", name: "能量源泉", effect: { type: "max_energy", value: 7 }, description: "能量值上限+7", score: 7 },

  // ==================== 抗性类 (14个) ====================
  { id: "pas_35", name: "火焰抗性", effect: { type: "resistance", damageTypes: ["火焰"] }, description: "获得【火焰】抗性", score: 3 },
  { id: "pas_36", name: "冰霜抗性", effect: { type: "resistance", damageTypes: ["冰霜"] }, description: "获得【冰霜】抗性", score: 3 },
  { id: "pas_37", name: "黑暗抗性", effect: { type: "resistance", damageTypes: ["黑暗"] }, description: "获得【黑暗】抗性", score: 3 },
  { id: "pas_38", name: "光明抗性", effect: { type: "resistance", damageTypes: ["光明"] }, description: "获得【光明】抗性", score: 3 },
  { id: "pas_39", name: "物理抗性", effect: { type: "resistance", damageTypes: ["物理"] }, description: "获得【物理】抗性", score: 4 },
  { id: "pas_40", name: "元素抗性", effect: { type: "resistance", damageTypes: ["火焰", "冰霜"] }, description: "获得【火焰】抗性、【冰霜】抗性", score: 5 },
  { id: "pas_41", name: "神圣抗性", effect: { type: "resistance", damageTypes: ["光明", "黑暗"] }, description: "获得【光明】抗性、【黑暗】抗性", score: 5 },
  { id: "pas_42", name: "全元素抗性", effect: { type: "resistance", damageTypes: ["火焰", "冰霜", "光明"] }, description: "获得【火焰】抗性、【冰霜】抗性、【光明】抗性", score: 6 },
  { id: "pas_43", name: "伤害减免", effect: { type: "resistance", damageTypes: ["物理", "火焰"] }, description: "获得【物理】抗性、【火焰】抗性", score: 5 },
  { id: "pas_44", name: "魔法免疫", effect: { type: "resistance", damageTypes: ["冰霜", "黑暗"] }, description: "获得【冰霜】抗性、【黑暗】抗性", score: 5 },
  { id: "pas_45", name: "闪电抗性", effect: { type: "resistance", damageTypes: ["闪电"] }, description: "获得【闪电】抗性", score: 3 },
  { id: "pas_46", name: "全属性抗性", effect: { type: "resistance", damageTypes: ["物理", "火焰", "冰霜"] }, description: "获得【物理】抗性、【火焰】抗性、【冰霜】抗性", score: 7 },
  { id: "pas_47", name: "绝对防御", effect: { type: "resistance", damageTypes: ["光明", "黑暗", "闪电"] }, description: "获得【光明】抗性、【黑暗】抗性、【闪电】抗性", score: 7 },
  { id: "pas_48", name: "元素免疫", effect: { type: "resistance", damageTypes: ["火焰", "冰霜", "闪电"] }, description: "获得【火焰】抗性、【冰霜】抗性、【闪电】抗性", score: 6 },

  // ==================== 攻击增强类 (9个) ====================
  { id: "pas_49", name: "武器大师", effect: { type: "attack", value: 1 }, description: "攻击加值+1", score: 3 },
  { id: "pas_50", name: "精准打击", effect: { type: "attack", value: 2 }, description: "攻击加值+2", score: 5 },
  { id: "pas_51", name: "战斗专家", effect: { type: "attack", value: 1 }, description: "攻击加值+1，闪避值+1", score: 5 },
  { id: "pas_52", name: "杀戮本能", effect: { type: "attack", value: 1 }, description: "攻击加值+1，格挡值+1", score: 5 },
  { id: "pas_53", name: "完美战士", effect: { type: "attack", value: 2 }, description: "攻击加值+2，闪避值+1", score: 6 },
  { id: "pas_54", name: "致命打击", effect: { type: "attack", value: 3 }, description: "攻击加值+3", score: 6 },
  { id: "pas_55", name: "战争机器", effect: { type: "attack", value: 2 }, description: "攻击加值+2，格挡值+1", score: 6 },
  { id: "pas_56", name: "暗影行者", effect: { type: "attack", value: 1 }, description: "攻击加值+1，闪避值+2", score: 6 },
  { id: "pas_57", name: "战斗大师", effect: { type: "attack", value: 2 }, description: "攻击加值+2，闪避值+1，格挡值+1", score: 7 },

  // ==================== 技能增强类 (9个) ====================
  { id: "pas_58", name: "运动健将", effect: { type: "skill", skill: "运动", value: 2 }, description: "运动+2", score: 2 },
  { id: "pas_59", name: "机械专家", effect: { type: "skill", skill: "机械", value: 2 }, description: "机械+2", score: 2 },
  { id: "pas_60", name: "隐秘大师", effect: { type: "skill", skill: "隐秘", value: 2 }, description: "隐秘+2", score: 2 },
  { id: "pas_61", name: "博学者", effect: { type: "skill", skill: "学识", value: 2 }, description: "学识+2", score: 2 },
  { id: "pas_62", name: "敏锐感知", effect: { type: "skill", skill: "察觉", value: 2 }, description: "察觉+2", score: 2 },
  { id: "pas_63", name: "社交达人", effect: { type: "skill", skill: "社交", value: 2 }, description: "社交+2", score: 2 },
  { id: "pas_64", name: "统御者", effect: { type: "skill", skill: "统御", value: 2 }, description: "统御+2", score: 2 },
  { id: "pas_65", name: "生存专家\(技能\)", effect: { type: "skill", skill: "生存", value: 2 }, description: "生存+2", score: 2 },
  { id: "pas_66", name: "全才", effect: { type: "multi_skill", skills: ["运动", "机械", "隐秘", "学识", "察觉"], value: 1 }, description: "运动+1，机械+1，隐秘+1，学识+1，察觉+1", score: 4 },

  // ==================== 怪物特攻类 (7个) ====================
  { id: "pas_67", name: "生灵猎手", effect: { type: "monster_attack_bonus", category: "类人生物", value: 1 }, description: "攻击【类人生物】时，攻击检定额外+1", score: 2 },
  { id: "pas_68", name: "亡骸克星", effect: { type: "monster_attack_bonus", category: "亡灵", value: 1 }, description: "攻击【亡灵】时，攻击检定额外+1", score: 2 },
  { id: "pas_69", name: "构装破坏者", effect: { type: "monster_attack_bonus", category: "构装体", value: 1 }, description: "攻击【构装体】时，攻击检定额外+1", score: 2 },
  { id: "pas_70", name: "元素猎手", effect: { type: "monster_attack_bonus", category: "元素体", value: 1 }, description: "攻击【元素体】时，攻击检定额外+1", score: 2 },
  { id: "pas_71", name: "异界驱逐者", effect: { type: "monster_attack_bonus", category: "异界生物", value: 1 }, description: "攻击【异界生物】时，攻击检定额外+1", score: 2 },
  { id: "pas_72", name: "生灵天敌", effect: { type: "monster_attack_bonus", category: "类人生物", value: 2 }, description: "攻击【类人生物】时，攻击检定额外+2", score: 4 },
  { id: "pas_73", name: "亡骸毁灭者", effect: { type: "monster_attack_bonus", category: "亡灵", value: 2 }, description: "攻击【亡灵】时，攻击检定额外+2", score: 4 },

  // ==================== 生命能量偷取类 (4个) ====================
  { id: "pas_74", name: "生命汲取", effect: { type: "life_steal", value: 1 }, description: "造成伤害时恢复自身1点生命值", score: 5 },
  { id: "pas_75", name: "能量汲取", effect: { type: "energy_steal", value: 1 }, description: "造成伤害时偷取对方1点能量值", score: 5 },
  { id: "pas_76", name: "噬魂者", effect: { type: "life_steal", value: 2 }, description: "造成伤害时恢复自身2点生命值", score: 7 },
  { id: "pas_77", name: "魔力吞噬", effect: { type: "energy_steal", value: 2 }, description: "造成伤害时偷取对方2点能量值", score: 7 },
];

// 辅助函数：按评分筛选能力
export function getAbilitiesByScoreRange<T extends { score: number }>(
  abilities: T[],
  min: number,
  max: number
): T[] {
  return abilities.filter((a) => a.score >= min && a.score <= max);
}

// 辅助函数：按稀有度获取能力数量配置
export function getAbilitySlots(quality: EquipmentQuality): { passive: number; active: number } {
  switch (quality) {
    case "普通":
      return { passive: 0, active: 0 };
    case "不凡":
      return { passive: 1, active: 0 };
    case "稀有":
      return { passive: 1, active: 1 };
    case "传说":
      return { passive: 2, active: 1 };
  }
}

// 按评分区间分类（用于生成器）
export const LOW_SCORE = { min: 1, max: 3 };
export const MID_SCORE = { min: 4, max: 6 };
export const HIGH_SCORE = { min: 7, max: 10 };
